# modified from
# https://github.com/haskell/vector/blob/master/.github/workflows/ci.yml
name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: '**'

defaults:
  run:
    shell: bash

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "8.8.4"  }
          - { cabal: "3.2", os: ubuntu-latest,  ghc: "8.10.3" }
          - { cabal: "3.4", os: ubuntu-latest,  ghc: "8.8.4"  }
          - { cabal: "3.4", os: ubuntu-latest,  ghc: "8.10.3" }
      fail-fast: false

    steps:
    # ----------------
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'
    # ----------------
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
    # ----------------
    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}--${{ github.Shah }}
    # ----------------
    - name: Versions
      run: |
        cabal -V
        ghc -V
    # ----------------
    - name: Build
      run: |
        ls
        pwd
        cabal build all
    # ----------------
    - name: Test
      run: |
        cabal test all
